### ISSUE TITLE
Server crash ::  Cannot read properties of undefined (reading '72')

### ISSUE THREAD

**Issue by acsid** [acsid/cawbemmo#37]
> worker --> Error Logged: TypeError: Cannot read properties of undefined (reading '72')
> TypeError: Cannot read properties of undefined (reading '72')
>    at Object.isTileBlocking (/home/vikingman/cawbemmo/src/server/world/physics.js:356:32)
>    at getTargetPos (/home/vikingman/cawbemmo/src/server/config/spells/spellFireblast.js:18:15)
>    at Object.cast (/home/vikingman/cawbemmo/src/server/config/spells/spellFireblast.js:103:24)
>    at Object.updateBase (/home/vikingman/cawbemmo/src/server/config/spells/spellTemplate.js:85:14)
>    at /home/vikingman/cawbemmo/src/server/components/spellbook.js:403:6
>    at Array.forEach (<anonymous>)
>    at Object.update (/home/vikingman/cawbemmo/src/server/components/spellbook.js:393:15)
>    at Object.update (/home/vikingman/cawbemmo/src/server/objects/objBase.js:74:11)
>    at Object.update (/home/vikingman/cawbemmo/src/server/objects/objects.js:325:7)
>    at Object.tick (/home/vikingman/cawbemmo/src/server/world/instancer.js:172:11)

**Comment by acsid** [comment]
#39 fix
